name: Code Coverage
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - run: ./gradlew checkstyleMain
      - run: ./gradlew test

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
         CC_TEST_REPORTER_ID: ${{secrets.CC_TOKEN}}
         JACOCO_SOURCE_PATH: ${{github.workspace}}/app/src/main/java
        with:
         coverageCommand: make report
         coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml
